### ISSUE TITLE
Ошибка при копировании картинки из Вопроса и вставки ее в графический редактор

### ISSUE THREAD

**Issue by DelmorS** [shmelev-1987/faq_net#1]
Добрый день!

При попытке скопировать картинку из любого сохраненного вопроса, и затем вставить ее в любой графический редактор (к примеру Paint) появляется ошибка "Данные из буфера обмена невозможно вставить"
При вставке в .doc .docx файлы все работает корректно

**Comment by shmelev-1987** [comment]
Добрый день!
Это происходит не со всеми картинками. Например, при вставке картинки из файла (пиктограмма "Добавить изображение") все нормально копируется. А если картинка была вставлена из Paint в заметку, то её можно открыть в Paint двойным щелчком.

**Comment by DelmorS** [comment]
> Добрый день!
> Это происходит не со всеми картинками. Например, при вставке картинки из файла (пиктограмма "Добавить изображение") все нормально копируется. А если картинка была вставлена из Paint в заметку, то её можно открыть в Paint двойным щелчком.

Да, вы правы
Если напрямую делать вставку картинку через меню Добавить картинку, все работает корректно
Проблема возникает только в том случае если:
1. Через Ctrl+C скопировать файл изображения из любого места (к примеру с Рабочего Стола)
2. Напрямую через Ctrl+V вставить файл в Вопрос, а не через меню Добавить картинку
Только в этом случае происходит ошибка

**Comment by shmelev-1987** [comment]
Это недостаток стандартного RichTextBox. Как вариант, можно сохранить заметку в RTF-файл и открыть например в Word или WordPad и оттуда скопировать изображение.
